apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: vehicle-quotes-db-memory-scaler
  namespace: capstone-project1  
spec:
  maxReplicas: 4
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 50Mi
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vehicle-quotes-db
