# k8s/dev/kustomization.yaml
kind: Kustomization

bases:
  - ../base

namespace: capstone-project1

resources:
  - web/persistent-volume.yaml
  - web/persistent-volume-claim.yaml
  - web/deployment.yaml

patches:
  - db/persistent-volume-host-path.yaml

images:
  - name: vehicle-quotes-web
    newName: ryansconsultant/vehicle-quotes-dev
    newTag: "2.0"
